version: '3'

services:
  nginx: 
    image: nginx:latest
    volumes: 
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8222:80'
    depends_on:
      - app 
    container_name: app_nginx

  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: app
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    environment:
        MYSQL_DATABASE: VacationSystem
        MYSQL_ROOT_PASSWORD: root
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - '8155:3306'
    container_name: vacation_system_mysql
